### PR TITLE
Made replies

### PR DESCRIPTION
**Pull request by Lukramancer**
Little QoL change. Replaced `message.channel.send` with `message.reply`. Made just blind replacement in two files based on [reply method docs](https://discordpy.readthedocs.io/en/stable/api.html#discord.Message.reply).

**WARNING: Haven't checked.**

### CODE REVIEW

**Comment by den0620** [comment]
I did it in sends because replies look unnatural
like do you really reply to each comment in usual conversation
but maybe LLM_LOCK, server down, and invalid config messages deserve it
also reply for /skip and /pov probably isnt a good idea

**Review by den0620 — CHANGES_REQUESTED** [review]
asyncmain should somewhen soon be moved into fallback
and
only server + config + lock messages make sense as replies

**Comment by Lukramancer** [comment]
So, only changes of `message.reply(full_content[len(old_content):])`, `message.reply("Reading tokens... <a:loadingP:1055187594973036576>")` and `await message.reply(text)` should be reverted?

**Comment by den0620** [comment]
> So, only changes of `message.reply(full_content[len(old_content):])`, `message.reply("Reading tokens... <a:loadingP:1055187594973036576>")` and `await message.reply(text)` should be reverted?

Yeah, but only the last two since I already moved asyncmain to fallback in latest commit and the first one as whole asyncmain is no longer needed

**Review by den0620 — APPROVED** [review]

**Pull request merged**
